language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sudo apt-get install colordiff
  - cd cloned
  - git clone https://github.com/zordius/lightncandy
  - cd lightncandy
  - git checkout -qf `cat ../../lightncandy`
  - cd ../..
  - cd report
  - phantomjs --local-to-remote-url-access=true ../bin/save-chart.js index.html?`ls *.json |tail -n 1`
  - cd ..
  - bin/push-report
script:
  - echo Tests based on this version... https://github.com/zordius/lightncandy/commit/`cat lightncandy`
  - php bin/hbreport F 28 T

env:
  global:
    secure: "Zed2cf/LuMUvaG33waSLDULC8J4SyWv0sT8I39wxVxOXUu8SkjrTiDK3k/kJo9NXyJOOrL+Wj1RdBDQzxaQDp6lMAcHHRl/JQk7SY/W1TJyp4STMlayrxlPM2rmFbB0Bz/3lB4CEZq7tzwKttGN80usBjkR9zLCFhNNFqklCAG8="
